// <auto-generated />
#nullable enable

namespace V_Launcher.Properties;

using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
internal static class Resources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal static ResourceManager ResourceManager =>
        resourceMan ??= new ResourceManager("V_Launcher.Properties.Resources", typeof(Resources).Assembly);

    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string LauncherOrderModeAlphabetical =>
        ResourceManager.GetString("LauncherOrderModeAlphabetical", resourceCulture) ?? string.Empty;

    internal static string LauncherOrderModeCustom =>
        ResourceManager.GetString("LauncherOrderModeCustom", resourceCulture) ?? string.Empty;

    internal static string LauncherOrderModeLabel =>
        ResourceManager.GetString("LauncherOrderModeLabel", resourceCulture) ?? string.Empty;

    internal static string LauncherOrderModeUpdateFailed =>
        ResourceManager.GetString("LauncherOrderModeUpdateFailed", resourceCulture) ?? string.Empty;

    internal static string LauncherOrderSaveFailed =>
        ResourceManager.GetString("LauncherOrderSaveFailed", resourceCulture) ?? string.Empty;
}
